### ISSUE TITLE
have you try this with postgres and did you change alembic

### ISSUE THREAD

**Issue by am1ru1** [joshua-hashimoto/fastapi-ormar#1]
Hi thank you for the code, 

Noticed that your alembic file was not changed, are you using Alembic with this?
sqlalchemy.url = driver://user:pass@localhost/dbname

And have you tried with postgres whether this setup and test works?

**Comment by joshua-hashimoto** [comment]
@am1ru1 
Hello!

> Noticed that your alembic file was not changed, are you using Alembic with this?

I am using Alembic with this!
I should have been more clean in my README.md, my bad.

I haven't set this in the alembic file because I wanted to make things as automatic as possible, so this setting is added to the `env.py`.

```py
config.set_main_option("sqlalchemy.url", get_db_url())
```

> And have you tried with postgres whether this setup and test works?

So I took this as whether I used postgresql as a test database and if it worked.
The answer is I haven't tried it.

My real world code is something like this.

```py
TEST_DB_URL = f"sqlite:///{str(settings.BASE_DIR)}/db/test_db.sqlite"


def get_db_uri(*, user, password, host, db, port="5432"):
    if settings.environment == "test":
        return TEST_DB_URL
    return f'postgresql://{user}:{password}@{host}:{port}/{db}'


DB_URL = get_db_uri(
    user=os.environ.get('POSTGRES_USER'),
    password=os.environ.get('POSTGRES_PASSWORD'),
    host='db',  # docker-compose service name
    db=os.environ.get('POSTGRES_DB'),
)
```

I use Docker for the real world code.
My goal was to switch the database to SQLite when testing, so I did just that.

So I imagine change the `TEST_DB_URL` to postgresql url should work fine.

Hope this helps!

**Comment by am1ru1** [comment]
I am currently refactoring from a very large code-base and so far your code seems to fit my objective. Appreciate your work, @joshua-hashimoto. Might have follow up questions :D
